/*
 * generated by Xtext
 */
package lu.uni.snt.repeat.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractREPEATValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(lu.uni.snt.repeat.rEPEAT.REPEATPackage.eINSTANCE);
		return result;
	}
}
