/*
 * generated by Xtext
 */
package lu.uni.snt.secan.ttc_xml.validation

import lu.uni.snt.secan.ttc_xml.tTC_XML.TTC_XMLPackage
import lu.uni.snt.secan.ttc_xml.tTC_XML.XMLNode
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class TTC_XMLValidator extends AbstractTTC_XMLValidator {

	@Check
	def checkXMLNodeHasStartEndTagsOfSameName(XMLNode xmlnode) {
		if (xmlnode.end != null && !xmlnode.tag.equals(xmlnode.end)) {
			error("Start-tag must have the name of its corresponding end-tag.", TTC_XMLPackage.Literals::XML_NODE__END);
			return;
		}
	}
	
}
