/*
 * generated by Xtext
 */
package lu.uni.snt.repeat;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class REPEATRuntimeModule extends lu.uni.snt.repeat.AbstractREPEATRuntimeModule {

}
