/*
* generated by Xtext
*/
package lu.uni.snt.repeat;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class REPEATStandaloneSetup extends REPEATStandaloneSetupGenerated{

	public static void doSetup() {
		new REPEATStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

