/**
 * generated by Xtext
 */
package de.tub.tfs.henshin.tgg.interpreter.config.validation;

import de.tub.tfs.henshin.tgg.interpreter.config.validation.AbstractTggInterpreterConfigValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TggInterpreterConfigValidator extends AbstractTggInterpreterConfigValidator {
}
