/*
 * generated by Xtext
 */
package lu.uni.snt.whileDSL.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import lu.uni.snt.whileDSL.ui.internal.WHILEActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WHILEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WHILEActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WHILEActivator.getInstance().getInjector(WHILEActivator.LU_UNI_SNT_WHILEDSL_WHILE);
	}
	
}
