/*
* generated by Xtext
*/
package lu.uni.snt.repeat;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class REPEATUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return lu.uni.snt.repeat.ui.internal.REPEATActivator.getInstance().getInjector("lu.uni.snt.repeat.REPEAT");
	}
	
}
