/*
* generated by Xtext
*/
package de.tub.tfs.henshin.tgg.interpreter.config.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.tub.tfs.henshin.tgg.interpreter.config.services.TggInterpreterConfigGrammarAccess;

public class TggInterpreterConfigParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TggInterpreterConfigGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected de.tub.tfs.henshin.tgg.interpreter.config.parser.antlr.internal.InternalTggInterpreterConfigParser createParser(XtextTokenStream stream) {
		return new de.tub.tfs.henshin.tgg.interpreter.config.parser.antlr.internal.InternalTggInterpreterConfigParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TggInterpreterConfig";
	}
	
	public TggInterpreterConfigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TggInterpreterConfigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
