/*
* generated by Xtext
*/
package de.tub.tfs.henshin.tgg.interpreter.config.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TggInterpreterConfigAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/tub/tfs/henshin/tgg/interpreter/config/parser/antlr/internal/InternalTggInterpreterConfig.tokens");
	}
}
