/*
 * generated by Xtext
 */
package lu.uni.snt.repeat.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class REPEATUiModule extends lu.uni.snt.repeat.ui.AbstractREPEATUiModule {
	public REPEATUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
