/*
 * generated by Xtext
 */
package lu.uni.snt.whileDSL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WHILEUiModule extends lu.uni.snt.whileDSL.ui.AbstractWHILEUiModule {
	public WHILEUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
