/*******************************************************************************
 * Copyright (c) 2010-2015 Henshin developers. All rights reserved. 
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     TU Berlin, University of Luxembourg, SES S.A.
 *******************************************************************************/
/*
 * generated by Xtext
 */
package lu.uni.snt.repeat.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import lu.uni.snt.repeat.ui.internal.REPEATActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class REPEATExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return REPEATActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return REPEATActivator.getInstance().getInjector(REPEATActivator.LU_UNI_SNT_REPEAT_REPEAT);
	}
	
}
