/*
* generated by Xtext
*/
package lu.uni.snt.whileDSL;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class WHILEUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return lu.uni.snt.whileDSL.ui.internal.WHILEActivator.getInstance().getInjector("lu.uni.snt.whileDSL.WHILE");
	}
	
}
