/*
 * generated by Xtext
 */
package lu.uni.snt.whileDSL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WHILERuntimeModule extends lu.uni.snt.whileDSL.AbstractWHILERuntimeModule {

}
