/*
* generated by Xtext
*/
package de.tub.tfs.henshin.tgg.interpreter.config;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TggInterpreterConfigUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.tub.tfs.henshin.tgg.interpreter.config.ui.internal.TggInterpreterConfigActivator.getInstance().getInjector("de.tub.tfs.henshin.tgg.interpreter.config.TggInterpreterConfig");
	}
	
}
