/*
* generated by Xtext
*/
package lu.uni.snt.whileDSL;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WHILEStandaloneSetup extends WHILEStandaloneSetupGenerated{

	public static void doSetup() {
		new WHILEStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

