/*
 * generated by Xtext
 */
package lu.uni.snt.repeat.ui.contentassist

import lu.uni.snt.repeat.ui.contentassist.AbstractREPEATProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class REPEATProposalProvider extends AbstractREPEATProposalProvider {
}
