<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tgg" nsURI="http://tgg.tu-berlin.de" nsPrefix="tgg">
  <eClassifiers xsi:type="ecore:EClass" name="TGG" eSuperTypes="../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcroot" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tarroot" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corresp" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodelayouts" upperBound="-1"
        eType="#//NodeLayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgelayouts" upperBound="-1"
        eType="#//EdgeLayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphlayouts" upperBound="-1"
        eType="#//GraphLayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tRules" upperBound="-1"
        eType="#//TRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="critPairs" upperBound="-1"
        eType="#//CritPair" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePkgs" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondencePkgs" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPkgs" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedPkgs" upperBound="-1"
        eType="#//ImportedPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TripleComponent">
    <eLiterals name="SOURCE"/>
    <eLiterals name="CORRESPONDENCE" value="1"/>
    <eLiterals name="TARGET" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsnode" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeLayouts" upperBound="-1"
        eType="#//AttributeLayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rhsTranslated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lhsTranslated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="critical" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsattribute" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsattribute" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsedge" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsedge" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rhsTranslated" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lhsTranslated" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="critical" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dividerX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Graph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSC" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CritPair">
    <eStructuralFeatures xsi:type="ecore:EReference" name="overlapping" eType="#//TripleGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule1" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule2" eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingsOverToRule1" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingsOverToRule2" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingsRule1ToRule2" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportedPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadWithDefaultValues"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" eType="#//TripleComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TripleGraph" eSuperTypes="../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Graph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dividerSC_X" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dividerCT_X" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dividerMaxY" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dividerYOffset" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TNode" eSuperTypes="../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" eType="#//TripleComponent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerType" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRule" eSuperTypes="../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMarked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manualMatchingOrder" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerType" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TEdge" eSuperTypes="../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Edge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerType" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAttribute" eSuperTypes="../../org.eclipse.emf.henshin.model/model/henshin.ecore#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerType" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
