/*
* generated by Xtext
*/
package lu.uni.snt.secan.ttc_xml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TTC_XMLStandaloneSetup extends TTC_XMLStandaloneSetupGenerated{

	public static void doSetup() {
		new TTC_XMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

