/*
 * generated by Xtext
 */
package lu.uni.snt.secan.ttc_xml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TTC_XMLRuntimeModule extends lu.uni.snt.secan.ttc_xml.AbstractTTC_XMLRuntimeModule {

}
