/*******************************************************************************
 * Copyright (c) 2010-2015 Henshin developers. All rights reserved. 
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     TU Berlin, University of Luxembourg, SES S.A.
 *******************************************************************************/
/*
 * generated by Xtext
 */
package lu.uni.snt.repeat.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class REPEATUiModule extends lu.uni.snt.repeat.ui.AbstractREPEATUiModule {
	public REPEATUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
