/*
* generated by Xtext
*/
package lu.uni.snt.whileDSL.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WHILEAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("lu/uni/snt/whileDSL/parser/antlr/internal/InternalWHILE.tokens");
	}
}
