/*
* generated by Xtext
*/
package lu.uni.snt.secan.ttc_java;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TTC_JavaStandaloneSetup extends TTC_JavaStandaloneSetupGenerated{

	public static void doSetup() {
		new TTC_JavaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

