/*
 * generated by Xtext
 */
package lu.uni.snt.secan.ttc_java;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TTC_JavaRuntimeModule extends lu.uni.snt.secan.ttc_java.AbstractTTC_JavaRuntimeModule {

}
