package agg.attribute.parser.javaExpr;

/* Generated By:JavaCC: Do not edit this line. JexParserConstants.java */
/**
 * @version $Id: JexParserConstants.java,v 1.7 2010/03/11 13:39:38 olga Exp $
 * @author $Author: olga $
 */
public interface JexParserConstants {

	static final long serialVersionUID = 1L;

	int EOF = 0;

	int INTEGER_LITERAL = 6;

	int DECIMAL_LITERAL = 7;

	int HEX_LITERAL = 8;

	int OCTAL_LITERAL = 9;

	int FLOATING_POINT_LITERAL = 10;

	int EXPONENT = 11;

	int CHARACTER_LITERAL = 12;

	int STRING_LITERAL = 13;

	int LPAREN = 14;

	int RPAREN = 15;

	int LBRACE = 16;

	int RBRACE = 17;

	int LBRACKET = 18;

	int RBRACKET = 19;

	int SEMICOLON = 20;

	int COMMA = 21;

	int DOT = 22;

	int DOLLAR = 23;

	int IDENTIFIER = 48;

	int LETTER = 49;

	int DIGIT = 50;

	int LONG_LITERAL = 51;

	int DEFAULT = 0;

	String[] tokenImage = { 
			"<EOF>", // 0
			"\" \"", // 1
			"\"\\t\"", // 2
			"\"\\n\"", // 3
			"\"\\r\"", // 4
			"\"\\f\"", // 5
			"<INTEGER_LITERAL>", // 6
			"<DECIMAL_LITERAL>", // 7
			"<HEX_LITERAL>", // 8
			"<OCTAL_LITERAL>", // 9
			"<FLOATING_POINT_LITERAL>", // 10
			"<EXPONENT>", // 11
			"<CHARACTER_LITERAL>", // 12
			"<STRING_LITERAL>", // 13
			"\"(\"", // 14
			"\")\"", // 15
			"\"{\"", // 16
			"\"}\"", // 17
			"\"[\"", // 18
			"\"]\"", // 19
			"\";\"", // 20
			"\",\"", // 21
			"\".\"", // 22
			"\"$\"", // 23
			"\"?\"", // 24
			"\":\"", // 25
			"\"||\"", // 26
			"\"&&\"", // 27
			"\"|\"", // 28
			"\"^\"", // 29
			"\"&\"", // 30
			"\"==\"", // 31
			"\"!=\"", // 32
			"\"<\"", // 33
			"\">\"", // 34
			"\"<=\"", // 35
			"\">=\"", // 36
			"\"+\"", // 37
			"\"-\"", // 38
			"\"*\"", // 39
			"\"/\"", // 40
			"\"%\"", // 41
			"\"~\"", // 42
			"\"!\"", // 43
			"\"new\"", // 44
			"\"true\"", // 45
			"\"false\"", // 46
			"\"null\"", // 47
			"<IDENTIFIER>", // 48
			"<LETTER>", // 49
			"<DIGIT>", // 50
			"<LONG_LITERAL>", // 51
			"\"\\\"" // 52
	};

}
/*
 * $Log: JexParserConstants.java,v $
 * Revision 1.7  2010/03/11 13:39:38  olga
 * test
 *
 * Revision 1.6  2008/01/14 08:46:42  olga
 * Bug fixed in using of CSP without Backjumping (CSP w/o BJ) match algorithm;
 * Bug fixed in using layered graph transformation with loop over layers.
 *
 * Revision 1.5  2007/09/10 13:05:47  olga
 * In this update:
 * - package xerces2.5.0 is not used anymore;
 * - class com.objectspace.jgl.Pair is replaced by the agg own generic class agg.util.Pair;
 * - bugs fixed in:  usage of PACs in rules;  match completion;
 * 	usage of static method calls in attr. conditions
 * - graph editing: added some new features
 * Revision 1.4 2007/05/07 07:59:37 olga CSP:
 * extentions of CSP variables concept
 * 
 * Revision 1.3 2007/02/19 09:11:01 olga Bug during loading file fixed. Type
 * editor tuning
 * 
 * Revision 1.2 2006/08/09 07:42:18 olga API docu
 * 
 * Revision 1.1 2005/08/25 11:56:52 enrico *** empty log message ***
 * 
 * Revision 1.1 2005/05/30 12:58:01 olga Version with Eclipse
 * 
 * Revision 1.4 2005/03/21 09:22:57 olga ...
 * 
 * Revision 1.3 2003/07/21 13:18:10 olga Attrs testen
 * 
 * Revision 1.2 2003/03/05 18:24:15 komm sorted/optimized import statements
 * 
 * Revision 1.1.1.1 2002/07/11 12:17:04 olga Imported sources
 * 
 * Revision 1.8 2000/04/05 12:10:56 shultzke serialVersionUID aus V1.0.0
 * generiert
 * 
 * Revision 1.7 2000/03/14 10:59:44 shultzke Transformieren von Variablen auf
 * Variablen sollte jetzt funktionieren Ueber das Design der Copy-Methode des
 * abstrakten Syntaxbaumes sollte unbedingt diskutiert werden.
 * 
 */
