<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TGG_correspondence" nsURI="http://snt.uni.lu/TGGcorrespondence"
    nsPrefix="TGGcorrespondence">
  <eClassifiers xsi:type="ecore:EClass" name="CORR">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tgt" eType="#//AbstractTarget"
        eOpposite="#//AbstractTarget/t2c"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="#//AbstractSource"
        eOpposite="#//AbstractSource/s2c"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="s2c" upperBound="-1" eType="#//CORR"
        eOpposite="#//CORR/src"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="t2c" upperBound="-1" eType="#//CORR"
        eOpposite="#//CORR/tgt"/>
  </eClassifiers>
</ecore:EPackage>
