/*
 * generated by Xtext
 */
package lu.uni.snt.whileDSL.ui.contentassist

import lu.uni.snt.whileDSL.ui.contentassist.AbstractWHILEProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class WHILEProposalProvider extends AbstractWHILEProposalProvider {
}
