<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="analysis"
    nsURI="http://www.eclipse.org/emf/2011/Henshin/Analysis" nsPrefix="analysis">
  <eClassifiers xsi:type="ecore:EClass" name="CriticalPair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CriticalPairType"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule1" eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule2" eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceUnit" eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//TransformationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetUnit" eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//TransformationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overlapping" eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingsOverlappingToRule1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingsOverlappingToRule2"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//Mapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingsRule1ToRule2" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2011/Henshin#//Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="criticalObjects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CausalityType">
    <eLiterals name="Initialization"/>
    <eLiterals name="Conflict" value="1"/>
    <eLiterals name="DependencyAlongControlflow" value="2"/>
    <eLiterals name="DependencyAgainstControlflow" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CriticalPairType">
    <eLiterals name="DELETE_USE_CONFLICT" literal="delete-use-conflict"/>
    <eLiterals name="DELETE_NEED_CONFLICT" value="1" literal="delete-need-conflict"/>
    <eLiterals name="PRODUCE_FORBID_CONFLICT" value="2" literal="produce-forbid-conflict"/>
    <eLiterals name="PRODUCE_EDGE_DELTE_NODE_CONFLICT" value="3" literal="produceEdge-deleteNode-conflict"/>
    <eLiterals name="CHANGE_USE_ATTR_CONFLICT" value="4" literal="change-use-attr-conflict"/>
    <eLiterals name="CHANGE_NEED_ATTR_CONFLICT" value="5" literal="change-need-attr-conflict"/>
    <eLiterals name="CHANGE_FORBID_ATTR_CONFLICT" value="6" literal="change-forbid-attr-conflict"/>
    <eLiterals name="DELETE_FORBID_DEPENDENCY" value="7" literal="produce-forbid-dependency"/>
    <eLiterals name="PRODUCE_USE_DEPENDENCY" value="8" literal="produce-use-dependency"/>
    <eLiterals name="PRODUCE_DELETE_DEPENDENCY" value="9" literal="produce-delete-dependency"/>
    <eLiterals name="PRODUCE_NEED_DEPENDENCY" value="10" literal="produce-need-dependency"/>
    <eLiterals name="CHANGE_USE_ATTR_DEPENDENCY" value="11" literal="change-use-attr-dependency"/>
    <eLiterals name="CHANGE_FORBID_ATTR_DEPENDENCY" value="12" literal="change-forbid-attr-dependency"/>
  </eClassifiers>
</ecore:EPackage>
