/**
 * generated by Xtext
 */
package de.tub.tfs.henshin.tgg.interpreter.config.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class TggInterpreterConfigScopeProvider extends AbstractDeclarativeScopeProvider {
}
