/*
* generated by Xtext
*/
package lu.uni.snt.repeat.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import lu.uni.snt.repeat.services.REPEATGrammarAccess;

public class REPEATParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private REPEATGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected lu.uni.snt.repeat.parser.antlr.internal.InternalREPEATParser createParser(XtextTokenStream stream) {
		return new lu.uni.snt.repeat.parser.antlr.internal.InternalREPEATParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RProgram";
	}
	
	public REPEATGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(REPEATGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
